name: Find Lowest Number Tests
on: [push]
jobs:
  test_numbers:
    name: Test Number Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test Case 1 - 10 numbers
      run: python3 find_lowest_number.py test_data/test1_input.txt actual1.txt
    - name: Compare Test 1 output
      run: diff test_data/test1_expected.txt actual1.txt
    - name: Test Case 2 - 1 number
      run: python3 find_lowest_number.py test_data/test2_input.txt actual2.txt
    - name: Compare Test 2 output
      run: diff test_data/test2_expected.txt actual2.txt
    - name: Test Case 3 - Blank file
      run: python3 find_lowest_number.py test_data/test3_input.txt actual3.txt
    - name: Compare Test 3 output
      run: diff test_data/test3_expected.txt actual3.txt
